sudo:
  required

language: java
jdk: openjdk8
services:
  - docker

#env:
#  global:
#    - COMMIT=${TRAVIS_COMMIT::7}
#    - secure: <encrypted_HEROKU_APP_NAME>
#    - secure: <encrypted_HEROKU_API_KEY>
#    - secure: <encrypted_D_USER>
#    - secure: <encrypted_D_PASS>

before_install:
  - docker pull openjdk:8-jdk-alpine

script:
  - mvn test
  - mvn clean package

# Create Docker image for our app and push it to Dockerhub repository and send messages to the Teams channel after the `script` job is successfully executed
after_success:
  - export COMMIT=${TRAVIS_COMMIT::7}
  - export TAG=`if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo "$TRAVIS_BRANCH--$COMMIT"; fi`
  - docker login -u $D_USER -p $D_PASS
  - docker-compose build
  - docker tag $HEROKU_APP_NAME:latest $HEROKU_APP_NAME:$TAG
  - docker push $HEROKU_APP_NAME:$TAG
  - export TITLE="$HEROKU_APP_NAME:$TAG is built properly and pushed to Dockerhub"
  - export TIMESTAMP=`date`
  - export GIT_LOG=`git log -1 --pretty=%B $COMMIT`
  - export TEXT="[build version] $TAG<br />[datetime] $TIMESTAMP<br />[changelog] $GIT_LOG<br />"
  - chmod +x send_to_teams.sh && ./send_to_teams.sh
# If the `script` job fails, it will send a failure message to Teams channel
after_failure:
  - export TITLE="Travis:$TRAVIS_JOB_ID -- build job is failed"
  - export TEXT=[datetime]:`date`

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
#  - docker login -u $D_USER -p $D_PASS
#  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
#  - export NAME=ainshigapov/docker-test-project
#  - docker build -t $NAME:$COMMIT .
#  - docker tag $NAME:$COMMIT $NAME:$TAG
#  - docker push $NAME

# Allow Travis to help deploy the app on Heroku
deploy:
  provider: heroku
  api-key:
    secure: "$HEROKU_API_KEY"
  app: my-springboot-helloworld
  on:
    tags: true
    repo: "$HEROKU_APP_NAME"

notifications:
  email:
    - ainshigapov@gmail.com